project:
  type: website

website:
  title: "Adam's Website"
  site-url: "https://adebenedictis2020.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



